services:
  postgres1:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db1'
      - 'POSTGRES_USER=user1'
      - 'POSTGRES_PASSWORD=pass1'
    ports:
      - '25432:5432'
    volumes:
      - ./init-db1.sql:/docker-entrypoint-initdb.d/init.sql

  postgres2:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db2'
      - 'POSTGRES_USER=user2'
      - 'POSTGRES_PASSWORD=pass2'
    ports:
      - '25433:5432'
    volumes:
      - ./init-db2.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: user-aggregator
    ports:
      - "8899:8899"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - postgres1
      - postgres2