data-sources:
  - name: database1
    strategy: postgres
    url: jdbc:postgresql://localhost:25432/db1
    user: user1
    password: pass1
    table: users
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name

  - name: database2
    strategy: postgres
    url: jdbc:postgresql://localhost:25433/db2
    user: user2
    password: pass2
    table: user_table
    mapping:
      id: ldap_login
      username: ldap_login
      name: name
      surname: surname